#!/bin/bash -

set_initial_pathloss()
{
 path_loss=80
 nems="1:100"
 device="letce0"

 date=`date +%H:%M:%S`
 echo "setting initial pathloss to $path_loss for $nems on device $device at $date"

 sleep 2

 emaneevent-pathloss $nems $path_loss -i $device

 echo "finished pathloss on device $device at $date"
}
